name: Publish Docker
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: strombergdev/frameio-python-sync/fio-sync
        username: ${{ github.actor }}
        password: ${{ github.password }}
        registry: docker.pkg.github.com
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
