name: Publish Docker
on:
  # This will only run when a new release is created, this means that pushes \
  # and merges to master wouldn't trigger a new publish.
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: strombergdev/frameio-python-sync/fio-sync # This might be right, could also be be strombergdev/fio-sync?
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
